### PR TITLE
spec: fix BR for libvirt-devel

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Review by marmarek — CHANGES_REQUESTED** [review]
Why? Upstream spec do have strict version dependency here.

**Comment by fepitre** [comment]
After testing the build on the latest sync commit it seems to pass on CentOS 8 now. Before, it was complaining about not finding the package. Not needed anymore.

**Comment by fepitre** [comment]
In fact I'm still having:
```
Error: 
 Problem: conflicting requests
  - package libvirt-devel-1000:6.3.0-1.centos8.x86_64 is excluded
```

**Comment by marmarek** [comment]
>   - package libvirt-devel-1000:6.3.0-1.centos8.x86_64 is excluded

That's definitely a problem, and allowing to install a different version isn't a solution...

**Pull request closed without merging**
