### PR TITLE
Add libvirt-python patches not yet included upstream

### PR DESCRIPTION
**Pull request by marmarek**
Patches for libvirtaio module, to be included upstream (hopefully in 3.8
version). Those should be updated with the final version (if will be different).

Cc @woju

### CODE REVIEW

**Comment by woju** [comment]
@marmarek you mind if I pushed a third patch which purports to fix QubesOS/qubes-issues#2805? I'd like to try "edit by maintaners" gh feature.

**Comment by marmarek** [comment]
Go ahead.

**Comment by marmarek** [comment]
Ok, since you didn't signed the commit, and also you can't push tag to my (PR author) repository, signature checking script can't find the signature. Not a big problem, I don't plan to fix it.

**Comment by marmarek** [comment]
@woju you need to add the patch to spec file.

**Pull request closed without merging**
