### PR TITLE
Reload libxl otherwise libvirt will use old libraries after update

### PR DESCRIPTION
**Pull request by fepitre**
From Marek's comment https://github.com/QubesOS/qubes-vmm-xen/pull/65/files?file-filters%5B%5D=.in#r336761710

### CODE REVIEW

**Review by marmarek — CHANGES_REQUESTED** [review]
This should be a trigger for relevant xen package (xen-libs?). So libvirt is restarted after Xen update - even if libvirt itself isn't updated.

**Comment by fepitre** [comment]
> This should be a trigger for relevant xen package (xen-libs?). So libvirt is restarted after Xen update - even if libvirt itself isn't updated.

Yes indeed.

**Comment by fepitre** [comment]
I switched to %triggerin macro.

**Comment by marmarek** [comment]
There may be an issue on major libvirt upgrade (see machinery with doing that in posttrans only). Generally it should be avoided to restart libvirt between individual libvirt package updates (like `libvirt-daemon` already updated, but `libvirt-daemon-driver-libxl` not yet). But this issue (if really applies) was also present with the previous solution, so this isn't really regression.
Worth testing, though.

**Review by marmarek — APPROVED** [review]
Loo

**Pull request merged**
