### PR TITLE
0017 patch: Add gfx_passthru option

### PR DESCRIPTION
**Pull request by cytadela8**
Required for Intel GPU passthrough.

QubesOS/qubes-issues#2618

### CODE REVIEW

**Comment by marmarek** [comment]
Since the patches this base on are already included in libvirt upstream master, I recommend sending this patch too.

**Comment by marmarek** [comment]
You need to also update relevant test - see build log in travis.

**Comment by marmarek** [comment]
> **policy/qubesos/code-signing ** — Unable to verify (no valid key found)

Please upload public key to a keyserver

**Comment by cytadela8** [comment]
Hmm, for me it shows the key is on pool.sks-keyservers.net 

```
gpg --keyserver pool.sks-keyservers.net --search-key contact@puzio.waw.pl
gpg: data source: http://62.210.187.135:11371
(1)     Artur Puzio <contact@puzio.waw.pl>
        Artur Puzio (GitHub commits) <cytadela8@users.noreply.github.com>
          4096 bit RSA key D87762204CFFE72F, utworzono: 2018-08-17
```

**Comment by marmarek** [comment]
As discussed on the libvirt mailing list, a better approach would be to automatically enable this option at libxl level. Here is the patch:
https://lists.xenproject.org/archives/html/xen-devel/2020-06/msg00471.html

We'll see what libxl maintainers will say (I guess "too late for Xen 4.14"), but I'd go with patching libxl like this instead of patching libvirt anyway. So, I'm closing this for now.
This also makes https://github.com/QubesOS/qubes-core-admin/commit/3e8f5a7a57e1be18710dd312ba46430ba9410a25 unnecessary (I'll revert it), and similarly setting this qvm-feature is not needed anymore.

**Pull request closed without merging**
